import React from 'react';
import { BookOpen, Cpu, ArrowRight, CheckCircle2, ShieldAlert } from 'lucide-react';

export default function IntroSection() {
  return (
    <div id="introduction" className="section-block">
      <div className="section-header-badge">Module 01</div>
      <h2 className="section-main-title">Introduction to Syntax Analysis</h2>

      {/* 1. What is Syntax Analysis */}
      <div className="card">
        <h3 className="card-title">
          <BookOpen size={20} /> What is Syntax Analysis?
        </h3>
        <p style={{ fontSize: '1rem', lineHeight: 1.65, color: 'var(--text-main)', marginBottom: '1rem' }}>
          <strong>Syntax Analysis</strong> (commonly referred to as <strong>Parsing</strong>) is the second phase of a compiler. Its primary objective is to verify whether the stream of tokens produced by the lexical analyzer conforms to the grammatical rules of the source programming language.
        </p>
        <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)' }}>
          While lexical analysis checks individual words (spelling/tokens), syntax analysis checks <strong>sentence structure (grammar)</strong>.
        </p>
      </div>

      {/* 2. What is a Parser */}
      <div className="card">
        <h3 className="card-title">
          <Cpu size={20} /> What is a Parser?
        </h3>
        <p style={{ fontSize: '1rem', lineHeight: 1.65, color: 'var(--text-main)' }}>
          A <strong>Parser</strong> is the software component or module within a compiler that performs syntax analysis. It takes a linear sequence of tokens, constructs a hierarchical parse tree, and reports any syntax errors encountered if the token stream violates language rules.
        </p>
      </div>

      {/* 3. Why is Syntax Analysis Needed? */}
      <div className="card" style={{ borderLeft: '4px solid var(--accent-color)' }}>
        <h3 className="card-title" style={{ color: 'var(--accent-color)' }}>
          Why is Syntax Analysis Needed?
        </h3>
        <p style={{ fontSize: '0.975rem', lineHeight: 1.6, color: 'var(--text-main)' }}>
          Lexical analysis alone is insufficient for compilation because scanner/lexers process code in a flat, linear manner. Lexical analysis can identify valid words (e.g., keywords, identifiers, operators), but it cannot check whether those words are arranged in a meaningful, nested hierarchy.
        </p>
        <div style={{ marginTop: '0.75rem', backgroundColor: 'var(--accent-light)', padding: '0.85rem 1rem', borderRadius: 'var(--radius-sm)', border: '1px solid #ebd4c2' }}>
          <strong>Example:</strong> Consider the invalid code <code>if + while * 42</code>.
          <br />
          A lexical analyzer accepts all 4 tokens as valid. Only the <strong>Parser</strong> detects that an operator <code>+</code> cannot immediately follow an <code>if</code> keyword.
        </div>
      </div>

      {/* 4. Input & Output of Parser */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.25rem', marginBottom: '1.5rem' }}>
        <div className="card">
          <h4 className="card-title" style={{ color: 'var(--primary-color)' }}>
            Input to Parser
          </h4>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem', lineHeight: 1.7, color: 'var(--text-main)' }}>
            <li>Stream of <strong>Tokens</strong> generated by Lexical Analyzer.</li>
            <li>Symbol table references for variable declarations.</li>
            <li>Formal Grammar specification (CFG).</li>
          </ul>
        </div>

        <div className="card">
          <h4 className="card-title" style={{ color: 'var(--success-color)' }}>
            Output of Parser
          </h4>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.925rem', lineHeight: 1.7, color: 'var(--text-main)' }}>
            <li>A hierarchical <strong>Parse Tree</strong> or <strong>Abstract Syntax Tree (AST)</strong>.</li>
            <li><strong>Syntax Errors</strong> (if grammatical rules are violated).</li>
          </ul>
        </div>
      </div>

      {/* 5. Lexical Analysis vs Syntax Analysis Comparison */}
      <div className="card">
        <h3 className="card-title">Lexical Analysis vs Syntax Analysis Comparison</h3>
        <table className="academic-table">
          <thead>
            <tr>
              <th>Property</th>
              <th>Lexical Analysis (Scanner)</th>
              <th>Syntax Analysis (Parser)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Primary Unit</strong></td>
              <td>Characters → Tokens</td>
              <td>Tokens → Syntactic Structure (Tree)</td>
            </tr>
            <tr>
              <td><strong>Formal Model</strong></td>
              <td>Regular Expressions & Finite Automata (DFA/NFA)</td>
              <td>Context-Free Grammar (CFG) & Pushdown Automata</td>
            </tr>
            <tr>
              <td><strong>Error Type Detected</strong></td>
              <td>Illegal characters, unclosed string literals</td>
              <td>Mismatched parentheses, missing semicolons, bad syntax</td>
            </tr>
            <tr>
              <td><strong>Structural View</strong></td>
              <td>Linear (1D stream)</td>
              <td>Hierarchical (2D tree structure)</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
